{
 "title": "Prima",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Endpoints Up?",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(probe_success, \"srv\", \"$1\", \"instance\", \"https://(.*?)/.*\")",
     "legendFormat": "{{srv}} {{job}}"
    }
   ]
  },
  {
   "title": "Response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "label_replace(probe_duration_seconds, \"srv\", \"$1\", \"instance\", \"https://(.*?)/.*\")",
     "legendFormat": "{{srv}} {{job}}"
    }
   ]
  },
  {
   "title": "Disk usage hopcroft",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(1-node_filesystem_avail_bytes{mountpoint=~\"/\"}/node_filesystem_size_bytes{mountpoint=~\"/\"}, \"srv\", \"$1\", \"instance\", \"hopcroft\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage hopcroft",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 16, "x": 8, "y": 8 },
   "targets": [
    { "expr": "node_load1", "legendFormat": "hopcroft" }
   ]
  },
  {
   "title": "Total registered users",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "prima_users_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total sessions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 4, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "prima_sessions_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total ODM requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 11, "x": 13, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "prima_requests_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Table scans per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(pg_db_stat_user_tables_seq_scan[10m])",
     "legendFormat": "{{relname}}"
    }
   ]
  },
  {
   "title": "Running transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "pg_db_stat_activity_transactions",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Deadlocks",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_server_stat_database_deadlocks{datname=\"prima\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}