//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

pub mod prelude;

pub mod assignment;
pub mod capacity;
pub mod company;
pub mod event;
pub mod user;
pub mod vehicle;
pub mod vehicle_specifics;
pub mod zone;
