//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "vehicle_specifics")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub seats: i32,
    pub wheelchairs: i32,
    pub storage_space: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::capacity::Entity")]
    Capacity,
    #[sea_orm(has_many = "super::vehicle::Entity")]
    Vehicle,
}

impl Related<super::capacity::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Capacity.def()
    }
}

impl Related<super::vehicle::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Vehicle.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
