//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "vehicle")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub license_plate: String,
    pub company: i32,
    pub specifics: i32,
    pub active: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::assignment::Entity")]
    Assignment,
    #[sea_orm(has_many = "super::availability::Entity")]
    Availability,
    #[sea_orm(
        belongs_to = "super::company::Entity",
        from = "Column::Company",
        to = "super::company::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Company,
    #[sea_orm(
        belongs_to = "super::vehicle_specifics::Entity",
        from = "Column::Specifics",
        to = "super::vehicle_specifics::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    VehicleSpecifics,
}

impl Related<super::assignment::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Assignment.def()
    }
}

impl Related<super::availability::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Availability.def()
    }
}

impl Related<super::company::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Company.def()
    }
}

impl Related<super::vehicle_specifics::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::VehicleSpecifics.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
